const flags = {
    korea: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/2560px-Flag_of_South_Korea.svg.png',
    isro: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/2560px-Flag_of_India.svg.png',
    jaxa: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/2560px-Flag_of_Japan.svg.png',
    esa: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/2560px-Flag_of_Europe.svg.png',
}

const spacecraftList =
    [
        {id: 'ace', title: 'Advanced Composition Explorer', mission: 'solar wind', location: 'heliocentric'},
        {id: 'apm1', title: 'Astrobotic Peregrine 1', mission: '', location: 'lunar'},
        {id: 'argo', title: 'ArgoMoon', mission: 'demo', location: 'deep space'},
        {id: 'atot', title: 'Advanced Tracking and Observational Techniques', mission: '', location: ''},
        {id: 'bepi', title: 'BepiColombo', mission: '', location: '', flag: flags.esa},
        {id: 'bios', title: 'BioSentinel', mission: '', location: ''},
        {id: 'caps', title: 'CAPSTONE', mission: 'orbit stability test', location: 'lunar'},
        {id: 'cas', title: 'Cassini', mission: '', location: ''},
        {id: 'cass', title: 'Testing', mission: 'maintenance', location: ''},
        {id: 'ch1', title: 'Chandrayaan', mission: '', location: 'lunar', flag: flags.isro},
        {id: 'ch2', title: 'Chandrayaan-2', mission: '', location: 'lunar', flag: flags.isro},
        {id: 'ch2l', title: 'Chandrayaan-2 Lander', mission: '', location: 'lunar', flag: flags.isro},
        {id: 'ch2o', title: 'Chandrayaan-2 Orbiter', mission: '', location: 'lunar', flag: flags.isro},
        {id: 'ch3', title: 'Chandrayaan-3', mission: '', location: 'lunar', flag: flags.isro},
        {id: 'chdr', title: 'Chandra Space Telescope', mission: 'X-ray Observatory', location: 'HEO'},
        {id: 'clu1', title: 'Cluster 1', mission: '', location: ''},
        {id: 'clu2', title: 'Cluster 2', mission: '', location: ''},
        {id: 'clu3', title: 'Cluster 3', mission: '', location: ''},
        {id: 'clu4', title: 'Cluster 4', mission: '', location: ''},
        {id: 'cue3', title: 'CU Earth Escape Explorer', mission: '', location: 'LEO'},
        {id: 'cusp', title: 'CubeSat for Solar Particles', mission: '', location: ''},
        {id: 'dart', title: 'Double Asteroid Redirection Test', mission: 'small body', location: 'small body',},
        {id: 'dawn', title: 'Dawn', mission: '', location: 'small body'},
        {id: 'dif', title: 'Deep Impact', mission: '', location: 'lunar'},
        {id: 'dsco', title: 'Deep Space Climate Observatory (DSCOVR)', mission: 'space weather', location: 'L1',},
        {id: 'dsn', title: 'Testing', mission: 'maintenance', location: ''},
        {id: 'dss', title: 'Testing', mission: 'maintenance', location: ''},
        {id: 'egs', title: 'EVN and Global Services', mission: '', location: ''},
        {id: 'em1', title: 'Human Space Flight: Artemis I', mission: '', location: ''},
        {id: 'em2', title: 'Human Space Flight: Artemis II', mission: '', location: ''},
        {id: 'em3', title: 'Human Space Flight: Artemis III', mission: '', location: ''},
        {id: 'emm', title: 'Emirates Mars Mission (Hope)', mission: '', location: 'Mars'},
        {id: 'em-1', title: 'Exploration Mission-1', mission: '', location: ''},
        {id: 'em-2', title: 'Exploration Mission-2', mission: '', location: ''},
        {id: 'em-3', title: 'Exploration Mission-3', mission: '', location: ''},
        {id: 'em-4', title: 'Exploration Mission-4', mission: '', location: ''},
        {id: 'em-5', title: 'Exploration Mission-5', mission: '', location: ''},
        {id: 'em-6', title: 'Exploration Mission-6', mission: '', location: ''},
        {id: 'em-7', title: 'Exploration Mission-7', mission: '', location: ''},
        {id: 'em-8', title: 'Exploration Mission-8', mission: '', location: ''},
        {id: 'em-9', title: 'Exploration Mission-9', mission: '', location: ''},
        {id: 'em-10', title: 'Exploration Mission-10', mission: '', location: ''},
        {
            id: 'equl',
            title: 'EQUilibriUm Lunar-Earth point 6U Spacecraft)',
            mission: 'mapping Earth plasmasphere',
            location: 'lunar',
            flag: flags.jaxa
        },
        {id: 'escg', title: 'Engineering and Science Contract Group', mission: '', location: ''},
        {
            id: 'eurc',
            title: 'Europa Clipper',
            mission: 'Europa\'s subsurface ocean',
            location: 'Jupiter (en-route)'
            ,
        },
        {id: 'eus', title: 'Exploration Upper Stage', mission: '', location: ''},
        {
            id: 'gaia',
            title: 'Gaia',
            mission: 'mapping Milky Way',
            location: 'L2',
            flag: flags.esa
        },
        {id: 'gbra', title: 'Ground Based Radio Astronomy', mission: 'radio telescope', location: ''},
        {id: 'go10', title: 'GOES 10', mission: 'weather', location: 'Earth'},
        {id: 'go11', title: 'GOES 11', mission: 'weather', location: 'Earth'},
        {id: 'go12', title: 'GOES 12', mission: 'weather', location: 'Earth'},
        {id: 'go13', title: 'GOES 13', mission: 'weather', location: 'Earth'},
        {id: 'go14', title: 'GOES 14', mission: 'weather', location: 'Earth'},
        {id: 'go15', title: 'GOES 15', mission: 'weather', location: 'Earth'},
        {id: 'go16', title: 'GOES 16', mission: 'weather', location: 'Earth'},
        {id: 'go17', title: 'GOES 17', mission: 'weather', location: 'Earth'},
        {id: 'grla', title: 'GRAIL A', mission: '', location: ''},
        {id: 'grlb', title: 'GRAIL B', mission: '', location: ''},
        {id: 'gssr', title: 'Solar System Radar', mission: 'NEO threat detection', location: 'Goldstone'},
        {id: 'gtl', title: 'Geotail', mission: '', location: ''},
        {id: 'gvrt', title: 'GAVRT', mission: 'radio telescope', location: 'Goldstone'},
        {id: 'hcra', title: 'Host Country Radio Astronomy', mission: '', location: ''},
        {id: 'hmap', title: 'LunaH-Map', mission: '', location: ''},
        {id: 'hst', title: 'Hubble Space Telescope', mission: '', location: ''},
        {id: 'hyb2', title: 'Hayabusa-2', mission: '', location: '', flag: flags.jaxa },
        {id: 'ice', title: 'ISEE-3 Reboot', mission: '', location: ''},
        {id: 'icps', title: 'Interim Cryogenic Propulsion Stage', mission: '', location: ''},
        {id: 'imag', title: 'IMAGE', mission: '', location: ''},
        {id: 'intg', title: 'INTEGRAL', mission: '', location: ''},
        {id: 'jno', title: 'Juno', mission: 'Jupiter\'s magnetosphere', location: 'Jupiter'},
        {id: 'jnsa', title: 'Janus A', mission: '', location: ''},
        {id: 'jnsb', title: 'Janus B', mission: '', location: ''},
        {id: 'jwst', title: 'James Webb Space Telescope', mission: 'early universe', location: 'L2'},
        {id: 'kepl', title: 'Kepler', mission: '', location: ''},
        {id: 'kplo', title: 'Korea Pathfinder Lunar Orbiter', mission: 'demonstration', location: 'Lunar', flag: flags.korea },
        {id: 'lade', title: 'Lunar Atmosphere and Dust Environment Explorer', mission: 'Moon\'s atmosphere', location: 'Lunar'},
        {id: 'lici', title: 'LICIACube', mission: '', location: ''},
        {id: 'lro', title: 'Lunar Reconnaissance Orbiter', mission: 'mapping the Moon', location: 'lunar'},
        {id: 'lnd1', title: 'Lunar Node 1', mission: '', location: ''},
        {id: 'ltst', title: 'Interim Cryogenic Propulsion Stage', mission: '', location: ''},
        {id: 'lucy', title: 'Lucy', mission: 'trojan asteroids', location: 'en-route'},
        {id: 'lunah-map', title: 'Lunar Hydrogen MAPper', mission: '', location: ''},
        {id: 'm01o', title: 'Mars Odyssey', mission: 'climate, geology, & radiation', location: 'Mars', },
        {id: 'm01s', title: 'Mars Odyssey', mission: 'climate, geology, & radiation', location: 'Mars', },
        {id: 'm20', title: 'Mars 2020 (Perseverance)', mission: 'rover', location: 'Mars'},
        {id: 'map', title: 'WMAP', mission: '', location: ''},
        {id: 'mcoa', title: 'MarCO A', mission: '', location: ''},
        {id: 'mcob', title: 'MarCO B', mission: '', location: ''},
        {id: 'mer1', title: 'Opportunity', mission: '', location: ''},
        {id: 'mer2', title: 'Spirit', mission: '', location: ''},
        {id: 'mex', title: 'Mars Express', mission: '', location: 'Mars'},
        {id: 'mgs', title: 'Mars Global Surveyor', mission: '', location: 'Mars'},
        {id: 'mlic', title: 'Lunar IceCube', mission: '', location: ''},
        {id: 'mms1', title: 'Magnetospheric Multiscale Mission 1', mission: 'Earth\'s magnetosphere', location: 'HEO'},
        {id: 'mms2', title: 'Magnetospheric Multiscale Mission 2', mission: 'Earth\'s magnetosphere', location: 'HEO'},
        {id: 'mms3', title: 'Magnetospheric Multiscale Mission 3', mission: 'Earth\'s magnetosphere', location: 'HEO'},
        {id: 'mms4', title: 'Magnetospheric Multiscale Mission 4', mission: 'Earth\'s magnetosphere', location: 'HEO'},
        {id: 'mom', title: 'Mars Orbiter Mission', mission: '', location: 'Mars'},
        {id: 'mro', title: 'Mars Reconnaissance Orbiter', mission: 'climate & geology', location: 'Mars', },
        {id: 'mros', title: 'Mars Reconnaissance Orbiter', mission: 'climate & geology', location: 'Mars', },
        {id: 'msgr', title: 'MESSENGER', mission: '', location: 'Mercury'},
        {id: 'msl', title: 'Mars Science Laboratory (Curiosity)', mission: 'rover', location: 'Mars'},
        {id: 'musc', title: 'Hayabusa', mission: '', location: ''},
        {id: 'mvn', title: 'MAVEN', mission: 'atmosphere', location: 'Mars'},
        {id: 'neas', title: 'Near Earth Asteroid Scout', mission: '', location: ''},
        {id: 'nhpc', title: 'New Horizons', mission: '', location: 'Pluto/Kuiper Belt'},
        {id: 'no15', title: 'NOAA 15', mission: 'weather', location: 'Earth'},
        {id: 'no16', title: 'NOAA 16', mission: 'weather', location: 'Earth'},
        {id: 'no17', title: 'NOAA 17', mission: 'weather', location: 'Earth'},
        {id: 'no18', title: 'NOAA 18', mission: 'weather', location: 'Earth'},
        {id: 'nsyt', title: 'InSight', mission: 'geology, atmosphere', location: 'Mars surface'},
        {id: 'olin', title: 'SWARM-EX', mission: '', location: ''},
        {id: 'omot', title: 'OMOTENASHI', mission: '', location: ''},
        {id: 'orx', title: 'OSIRIS-REx', mission: 'small body sample', location: 'asteroid Apophis (en-route)', },
        {id: 'phx', title: 'Phoenix', mission: '', location: ''},
        {id: 'plc', title: 'Akatsuki', mission: '', location: ''},
        {id: 'polr', title: 'POLAR', mission: '', location: ''},
        {id: 'psyc', title: 'Psyche', mission: 'planet formation', location: 'Asteroid 16 Psyche (en-route', },
        {id: 'rd1', title: 'Red Dragon 1', mission: '', location: ''},
        {id: 'rfc', title: 'Reference Frame Calibration', mission: '', location: ''},
        {id: 'rose', title: 'Rosetta', mission: '', location: ''},
        {id: 'rp', title: 'Resource Prospector', mission: '', location: ''},
        {id: 'rsp', title: 'ExoMars Rover and Surface Platform', mission: '', location: '', flag: flags.esa },
        {id: 'rsts', title: 'Resource System Time Sharing', mission: '', location: ''},
        {id: 'sdu', title: 'Stardust', mission: '', location: ''},
        {id: 'sele', title: 'Kaguya', mission: '', location: ''},
        {id: 'sgp', title: 'Space Geodesy Program', mission: '', location: ''},
        {id: 'slim', title: 'Smart Lander for Investigating Moon', mission: '', location: ''},
        {id: 'soho', title: 'SOlar Heliophisics Observatory', mission: 'heliophysics', location: 'L1', },
        {id: 'spil', title: 'Beresheet', mission: '', location: ''},
        {id: 'spp', title: 'Parker Solar Probe', mission: 'Sun\'s corona', location: 'HEO'},
        {id: 'sta', title: 'STEREO A', mission: 'heliophysics', location: 'trojan'},
        {id: 'stab', title: 'STEREO B', mission: 'heliophysics', location: 'trojan'},
        {id: 'stb', title: 'STEREO B', mission: 'heliophysics', location: 'trojan'},
        {id: 'stf', title: 'Spitzer Space Telescope', mission: '', location: ''},
        {id: 'td10', title: 'TDRS 10', mission: '', location: 'LEO'},
        {id: 'td11', title: 'TDRS 11', mission: '', location: 'LEO'},
        {id: 'td12', title: 'TDRS 12', mission: '', location: 'LEO'},
        {id: 'td13', title: 'TDRS 13', mission: '', location: 'LEO'},
        {id: 'tdr1', title: 'TDRS 1', mission: '', location: 'LEO'},
        {id: 'tdr3', title: 'TDRS 3', mission: '', location: 'LEO'},
        {id: 'tdr4', title: 'TDRS 4', mission: '', location: 'LEO'},
        {id: 'tdr5', title: 'TDRS 5', mission: '', location: 'LEO'},
        {id: 'tdr6', title: 'TDRS 6', mission: '', location: 'LEO'},
        {id: 'tdr7', title: 'TDRS 7', mission: '', location: 'LEO'},
        {id: 'tdr8', title: 'TDRS 8', mission: '', location: 'LEO'},
        {id: 'tdr9', title: 'TDRS 9', mission: '', location: 'LEO'},
        {id: 'terr', title: 'TERRA', mission: '', location: ''},
        {id: 'tess', title: 'Transiting Exoplanet Survey Satellite', mission: '', location: ''},
        {id: 'tgo', title: 'Trace Gas Orbiter', mission: 'atmosphere', location: 'Mars', flag: flags.esa },
        {id: 'thb', title: 'THEMIS B', mission: 'Earth\'s magnetosphere', location: 'LEO'},
        {id: 'thc', title: 'THEMIS C', mission: '', location: ''},
        {id: 'tm', title: 'Team Miles', mission: '', location: ''},
        {id: 'tmm', title: 'Team Miles', mission: '', location: ''},
        {id: 'ulys', title: 'Ulysses', mission: '', location: ''},
        {id: 'vex', title: 'Venus Express', mission: '', location: ''},
        {id: 'vgr1', title: 'Voyager 1', mission: 'beyond the solar system', location: 'interstellar', },
        {id: 'vgr2', title: 'Voyager 2', mission: 'beyond the solar system', location: 'interstellar', },
        {id: 'vlbi', title: 'V.L.B. Interferometry', mission: '', location: ''},
        {id: 'wind', title: 'WIND', mission: 'solar wind', location: 'L1'},
        {id: 'xmm', title: 'X-ray Multi-Mirror Mission (XMM-Newton)', mission: '', location: ''},
    ]

const spacecraftMap = spacecraftList.reduce((result, dict) => {
    result[dict.id] = dict;
    result[dict.id].last_dish = null;
    result[dict.id].last_site = null;
    result[dict.id].total_down = 0;
    result[dict.id].first_seen = null;
    result[dict.id].total_sec = 10; // seed at refresh rate
    return result;
}, {});
